# Generated by Django 5.0.2 on 2024-02-27 14:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50)),
                ('account_balance', models.IntegerField()),
                ('account_holder_name', models.CharField(max_length=75)),
                ('account_type', models.CharField(max_length=20)),
                ('iso_currency_code', models.CharField(max_length=3)),
                ('account_limit', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_method', models.CharField(max_length=20)),
                ('transaction_amount', models.IntegerField()),
                ('merchant_entity_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('iso_currency_code', models.CharField(max_length=3)),
                ('transaction_date', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
