# Generated by Django 5.0.2 on 2024-02-28 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('bond_name', models.CharField(max_length=50)),
                ('face_value', models.IntegerField()),
                ('coupon_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('maturity_date', models.CharField(max_length=50)),
                ('current_price', models.IntegerField()),
                ('yield_to_maturity', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('fixed_deposit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('tenure_months', models.IntegerField()),
                ('maturity_amount', models.IntegerField()),
                ('maturity_date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=50)),
                ('fund_type', models.CharField(max_length=50)),
                ('fund_manager', models.CharField(max_length=50)),
                ('nav', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fund_rating', models.CharField(max_length=50)),
                ('minimum_investment', models.IntegerField()),
                ('expense_ratio', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_symbol', models.CharField(max_length=50)),
                ('current_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=6, max_digits=12)),
                ('volume', models.IntegerField()),
                ('market_cap', models.IntegerField()),
                ('pe_ratio', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_date',
        ),
    ]
