# Generated by Django 5.0.2 on 2024-02-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transactions_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_date',
        ),
    ]
