# Generated by Django 5.0.2 on 2024-02-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_transactions_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
