# Generated by Django 5.0.2 on 2024-02-29 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transactions_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('policy_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_holder', models.CharField(max_length=50)),
                ('policy_type', models.CharField(max_length=50)),
                ('premium_amount', models.IntegerField()),
                ('coverage_amount', models.IntegerField()),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=50)),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('term_months', models.IntegerField()),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidentFund',
            fields=[
                ('ppf_account_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
                ('annual_contribution', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('maturity_date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
